trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.6.6'

- script: |
    terraform init
    terraform validate
    terraform plan -out=tfplan
    terraform apply -auto-approve tfplan
  workingDirectory: terraform-vm
  displayName: 'Terraform Init, Plan and Apply'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
